### PR TITLE
Port to NET Core

### PR DESCRIPTION
**Pull request by grbsk**
Targets both .NET Core Standard and .NET Framework 4.5+
# Motivations
- Prep project for consumption by .NET Core libraries and applications
- Add support for non-Windows or .NET Framework platforms
- Maintain support for existing .NET Framework 4.5+ applications
- Single Repo for all targets
- Better nuget tooling
# Breaking Changes
- (DEV) Must be running VS2015 with Microsoft .NET Core RC2 tools installed (this will also install the .NET Core SDK)
- `IdGen.Configuration` namespace and `IdGenerator.GetFromConfig` not supported on NET Core Standard, as `System.Configuration` has been deprecated and will not be migrated to .NET Core.
# TODOs
- [ ] Fix appveyor build script to use `dotnet restore` before building and running tests.
- [ ] Create new or update nuget publishing tooling using [`dotnet publish`](https://dotnet.github.io/docs/core-concepts/core-sdk/cli/dotnet-publish.html) 
- [ ] Remove .nuget (thankfully not needed anymore)
- [ ] Ensure doc project works as expected
- [ ] Investigate if there's anything to do to replace IdGen.Configuration API for .NET Core users
- [ ] Let project.json version the assembly (remove `AssemblyVersion` etc. from AssemblyInfo.cs)
- [ ] Create test running task to make it easier to run tests for all supported frameworks
# Misc.
- Use compilation directives to vary source based on target framework: `#if NET45 ... #else .. #endif`
- `IdGenTests` must target .NET Framework 4.5.1 because of tool dependendencies. Shouldn't have any effect on consumers.
- Tests can be run by using the `dotnet test` CLI in the `IdGenTests` folder:
  - `dotnet test` will build and run the tests for .NET Core Standard
  - `dotnet test -f net451` will build and run tests for .NET Framework 4.5.1

### CODE REVIEW

**Comment by dotnetchris** [comment]
@RobThree have you looked into merging this yet? i was about to try to use this project but...

Actually just found there's a fork from someone else https://github.com/joshclark/Flakey

**Comment by RobThree** [comment]
Haven't looked into it thoroughly. Firstly because I have near-zero experience with .Net Core so I'm not sure wether all of this is anything near 'correct'; secondly because it has still a bunch of "todo's" that need to be looked at and thirdly because since this PR [a lot has changed](https://github.com/RobThree/IdGen/commit/7fc912064703774db27e7ff70d878f46debad60f).

I didn't know about the fork; a heads-up would've been nice and appreciated; not sure why @joshclark chose not to.

**Comment by joshclark** [comment]
@RobThree, sorry about the lack of notice.  I wasn't trying to be rude and I didn't mean any offense by it.

**Comment by RobThree** [comment]
@joshclark No offense taken, nor do I think it was "rude". It's just nice to know when your project is forked; maybe we can actually help each-other on this-or-that.

**Comment by grbsk** [comment]
I will update the PR with the latest from upstream master. Most of those items in my todo I can offer opinion or assistance on, but either can't do myself (I don't have access to the repo's appveyor config, nor do I know appveyor at all) or requires the input of the owner @RobThree (for example, how to make it work with how you build, test, and publish, and how to replace the existing doc project since AFAIK it won't work in VS2015 or with XPROJ).

I'm happy to explain the particulars about the items in the TODO to find the answer and get this merged. .NET Core is an important development in the .NET ecosystem, and unless you see this only being a purpose-built or legacy (by that I mean, plain old .NET Framework only) package, the sooner we roll support for .NET Core the better (and more popular) it'll be.

**Comment by RobThree** [comment]
A lot has changed since this PR in DotNet Core and [in this project as well](https://github.com/RobThree/IdGen/pull/2#issuecomment-242485022). I'd love to port to DotNet Core but I think another stab at it would be warranted.

**Pull request closed without merging**
